import { Text, View, StyleSheet, ScrollView } from "react-native"
import VerticalList from "../components/verticalList"
import { useState } from "react"

const Favorites = () => {
    const [data, setData] = useState([
        {
      "ano": 2022,
      "capacidade_de_passageiros": 5,
      "consumo_de_combustivel": "24 mpg (cidade), 32 mpg (estrada)",
      "cor_exterior": "Cinza",
      "cor_interior": "Preto",
      "disponivel": true,
      "id": 10,
      "imagem": "https://www.powerimports.com.br/restrito/img/veiculos_seminovos/187/1622605841-162260584160b7001128aac.jpg",
      "marca": "Kia",
      "modelo": "Sportage",
      "motor": "4 cilindros 2.4L",
      "numero_de_portas": 4,
      "potencia": 181,
      "preco_por_dia": 48,
      "quilometragem": "11,000 milhas",
      "recursos": [
        "Tela Sensível ao Toque",
        "Câmera de Visão Traseira",
        "Controle de Estabilidade"
      ],
      "tipo_de_combustivel": "Gasolina",
      "torque": "175 lb-ft",
      "transmissao": "Automática",
      "velocidade_maxima": "125 mph",
      "versao": "LX"
    },
    {
      "ano": 2022,
      "capacidade_de_passageiros": 5,
      "consumo_de_combustivel": "25 mpg (cidade), 28 mpg (estrada)",
      "cor_exterior": "Prata",
      "cor_interior": "Preto",
      "disponivel": true,
      "id": 12,
      "imagem": "https://img.clasf.com.br/2021/07/17/Hyundai-Santa-F-3-3-V6-Prata-20172018-Goinia-1474186-20210717144835.7552750015.jpg",
      "marca": "Hyundai",
      "modelo": "Santa Fe",
      "motor": "4 cilindros 2.5L",
      "numero_de_portas": 4,
      "potencia": 191,
      "preco_por_dia": 54,
      "quilometragem": "14,000 milhas",
      "recursos": [
        "Tela Touchscreen de 8 polegadas",
        "Câmera de Ré",
        "Alerta de Colisão Frontal"
      ],
      "tipo_de_combustivel": "Gasolina",
      "torque": "181 lb-ft",
      "transmissao": "Automática",
      "velocidade_maxima": "125 mph",
      "versao": "SE"
    },
    {
      "ano": 2022,
      "capacidade_de_passageiros": 5,
      "consumo_de_combustivel": "20 mpg (cidade), 28 mpg (estrada)",
      "cor_exterior": "Branco",
      "cor_interior": "Cinza",
      "disponivel": true,
      "id": 13,
      "imagem": "https://th.bing.com/th/id/R.61a7cc10ee204111bc08af1dfafc6f13?rik=AqA8zt1KEv8T2g&riu=http%3a%2f%2fwww.car-revs-daily.com%2fwp-content%2fuploads%2f2015%2f11%2f2016-Lexus-RX350-Eminent-White-Pearl-41.jpg&ehk=sD2gODToU9DmIffMLpS82yJmqc3DWgK2dq1ShKB0h80%3d&risl=&pid=ImgRaw&r=0",
      "marca": "Lexus",
      "modelo": "RX",
      "motor": "V6 3.5L",
      "numero_de_portas": 4,
      "potencia": 295,
      "preco_por_dia": 70,
      "quilometragem": "10,000 milhas",
      "recursos": [
        "Bancos de Couro",
        "Sistema de Navegação",
        "Teto Solar Panorâmico"
      ],
      "tipo_de_combustivel": "Gasolina Premium",
      "torque": "267 lb-ft",
      "transmissao": "Automática",
      "velocidade_maxima": "130 mph",
      "versao": "350"
    },
    {
      "ano": 2022,
      "capacidade_de_passageiros": 5,
      "consumo_de_combustivel": "27 mpg (cidade), 37 mpg (estrada)",
      "cor_exterior": "Azul",
      "cor_interior": "Preto",
      "disponivel": true,
      "id": 16,
      "imagem": "https://inv.assets.sincrod.com/ChromeColorMatch/us/WHITE_cc_2019NIC040006_02_1280_RAY.jpg",
      "marca": "Nissan",
      "modelo": "Altima",
      "motor": "2.5L 4-cilindros",
      "numero_de_portas": 4,
      "potencia": 188,
      "preco_por_dia": 55,
      "quilometragem": "12,000 milhas",
      "recursos": [
        "Sistema de Navegação",
        "Teto Solar",
        "Câmera 360°"
      ],
      "tipo_de_combustivel": "Gasolina",
      "torque": "180 lb-ft",
      "transmissao": "Automática",
      "velocidade_maxima": "125 mph",
      "versao": "SV"
    },
    {
      "ano": 2022,
      "capacidade_de_passageiros": 5,
      "consumo_de_combustivel": "31 mpg (cidade), 41 mpg (estrada)",
      "cor_exterior": "Branco",
      "cor_interior": "Cinza",
      "disponivel": true,
      "id": 18,
      "imagem": "https://i.ytimg.com/vi/rqAxZ6YTJ-Y/maxresdefault.jpg",
      "marca": "Hyundai",
      "modelo": "Elantra",
      "motor": "2.0L 4-cilindros",
      "numero_de_portas": 4,
      "potencia": 147,
      "preco_por_dia": 52,
      "quilometragem": "11,000 milhas",
      "recursos": [
        "Teto Solar Panorâmico",
        "Assentos de Couro",
        "Sistema de Áudio Premium"
      ],
      "tipo_de_combustivel": "Gasolina",
      "torque": "132 lb-ft",
      "transmissao": "Automática",
      "velocidade_maxima": "120 mph",
      "versao": "Limited"
    },
    {
      "ano": 2022,
      "capacidade_de_passageiros": 5,
      "consumo_de_combustivel": "25 mpg (cidade), 31 mpg (estrada)",
      "cor_exterior": "Azul",
      "cor_interior": "Preto",
      "disponivel": true,
      "id": 20,
      "imagem": "https://s3.amazonaws.com/dercocenter.cl/uploads/sites/6/2017/10/mazda-cx-5-galeria-ficha-exterior-10-1.jpg",
      "marca": "Mazda",
      "modelo": "CX-5",
      "motor": "2.5L 4-cilindros",
      "numero_de_portas": 4,
      "potencia": 187,
      "preco_por_dia": 58,
      "quilometragem": "13,000 milhas",
      "recursos": [
        "Tela de Toque Infotainment",
        "Câmera 360°",
        "Assentos Aquecidos"
      ],
      "tipo_de_combustivel": "Gasolina",
      "torque": "186 lb-ft",
      "transmissao": "Automática",
      "velocidade_maxima": "125 mph",
      "versao": "Touring"
    },
    {
      "ano": 2022,
      "capacidade_de_passageiros": 5,
      "consumo_de_combustivel": "24 mpg (cidade), 34 mpg (estrada)",
      "cor_exterior": "Preto",
      "cor_interior": "Cinza",
      "disponivel": true,
      "id": 22,
      "imagem": "https://4.bp.blogspot.com/-qYY1-tuYVAo/ULwGrW-F7hI/AAAAAAAAs9E/qxZa_9agDJE/s1600/Audi-A4-Attraction+(11).JPG",
      "marca": "Audi",
      "modelo": "A4",
      "motor": "2.0L 4-cilindros",
      "numero_de_portas": 4,
      "potencia": 201,
      "preco_por_dia": 80,
      "quilometragem": "10,000 milhas",
      "recursos": [
        "Tela MMI Touch",
        "Teto Solar",
        "Sistema de Som Bang & Olufsen"
      ],
      "tipo_de_combustivel": "Gasolina Premium",
      "torque": "236 lb-ft",
      "transmissao": "Automática",
      "velocidade_maxima": "130 mph",
      "versao": "Premium Plus"
    },
    {
      "ano": 2022,
      "capacidade_de_passageiros": 5,
      "consumo_de_combustivel": "20 mpg (cidade), 27 mpg (estrada)",
      "cor_exterior": "Branco",
      "cor_interior": "Cinza",
      "disponivel": true,
      "id": 24,
      "imagem": "https://th.bing.com/th/id/R.61a7cc10ee204111bc08af1dfafc6f13?rik=AqA8zt1KEv8T2g&riu=http%3a%2f%2fwww.car-revs-daily.com%2fwp-content%2fuploads%2f2015%2f11%2f2016-Lexus-RX350-Eminent-White-Pearl-41.jpg&ehk=sD2gODToU9DmIffMLpS82yJmqc3DWgK2dq1ShKB0h80%3d&risl=&pid=ImgRaw&r=0",
      "marca": "Lexus",
      "modelo": "RX",
      "motor": "3.5L V6",
      "numero_de_portas": 4,
      "potencia": 295,
      "preco_por_dia": 75,
      "quilometragem": "9,000 milhas",
      "recursos": [
        "Sistema de Áudio Mark Levinson",
        "Assentos de Couro",
        "Teto Solar Panorâmico"
      ],
      "tipo_de_combustivel": "Gasolina",
      "torque": "267 lb-ft",
      "transmissao": "Automática",
      "velocidade_maxima": "130 mph",
      "versao": "350"
    },
    {
      "ano": 2022,
      "capacidade_de_passageiros": 5,
      "consumo_de_combustivel": "27 mpg (cidade), 37 mpg (estrada)",
      "cor_exterior": "Azul",
      "cor_interior": "Bege",
      "disponivel": true,
      "id": 26,
      "imagem": "https://www.coches.com/fotos_historicas/nissan/Altima-SR-2015/nissan_altima-sr-2015_r6.jpg",
      "marca": "Nissan",
      "modelo": "Altima",
      "motor": "2.5L 4-cilindros",
      "numero_de_portas": 4,
      "potencia": 188,
      "preco_por_dia": 60,
      "quilometragem": "12,000 milhas",
      "recursos": [
        "Sistema de Navegação",
        "Câmera de Ré",
        "Conexão USB"
      ],
      "tipo_de_combustivel": "Gasolina",
      "torque": "180 lb-ft",
      "transmissao": "Automática",
      "velocidade_maxima": "125 mph",
      "versao": "SV"
    },
    {
      "ano": 2022,
      "capacidade_de_passageiros": 5,
      "consumo_de_combustivel": "26 mpg (cidade), 33 mpg (estrada)",
      "cor_exterior": "Verde",
      "cor_interior": "Cinza",
      "disponivel": true,
      "id": 28,
      "imagem": "https://bengold.tv/wp-content/uploads/2019/07/Subaru-Outback-2020-verde.jpg",
      "marca": "Subaru",
      "modelo": "Outback",
      "motor": "2.5L 4-cilindros",
      "numero_de_portas": 4,
      "potencia": 182,
      "preco_por_dia": 65,
      "quilometragem": "11,000 milhas",
      "recursos": [
        "Tração nas Quatro Rodas",
        "Tela Sensível ao Toque",
        "Assentos Aquecidos"
      ],
      "tipo_de_combustivel": "Gasolina",
      "torque": "176 lb-ft",
      "transmissao": "Automática",
      "velocidade_maxima": "125 mph",
      "versao": "Limited"
    },
    {
      "ano": 2022,
      "capacidade_de_passageiros": 7,
      "consumo_de_combustivel": "24 mpg (cidade), 29 mpg (estrada)",
      "cor_exterior": "Cinza",
      "cor_interior": "Preto",
      "disponivel": true,
      "id": 31,
      "imagem": "https://img2.icarros.com/dbimg/imgadicionalanuncio/5/201016786_1.jpg",
      "marca": "Kia",
      "modelo": "Sorento",
      "motor": "2.5L 4-cilindros",
      "numero_de_portas": 4,
      "potencia": 191,
      "preco_por_dia": 50,
      "quilometragem": "10,000 milhas",
      "recursos": [
        "Terceira Fila de Bancos",
        "Câmera Traseira",
        "Controle de Clima Dual Zone"
      ],
      "tipo_de_combustivel": "Gasolina",
      "torque": "182 lb-ft",
      "transmissao": "Automática",
      "velocidade_maxima": "125 mph",
      "versao": "LX"
    },
    {
      "ano": 2022,
      "capacidade_de_passageiros": 5,
      "consumo_de_combustivel": "23 mpg (cidade), 33 mpg (estrada)",
      "cor_exterior": "Preto",
      "cor_interior": "Preto",
      "disponivel": true,
      "id": 33,
      "imagem": "https://ag-spots-2014.o.auroraobjects.eu/2014/10/08/other/2880-1800-crop-mercedes-benz-c-63-amg-coupe-black-series-c604508102014184950_1.jpg",
      "marca": "Mercedes-Benz",
      "modelo": "C-Class",
      "motor": "2.0L 4-cilindros",
      "numero_de_portas": 4,
      "potencia": 255,
      "preco_por_dia": 85,
      "quilometragem": "5,000 milhas",
      "recursos": [
        "Teto Solar Panorâmico",
        "Sistema de Navegação",
        "Assentos de Couro"
      ],
      "tipo_de_combustivel": "Gasolina Premium",
      "torque": "273 lb-ft",
      "transmissao": "Automática",
      "velocidade_maxima": "140 mph",
      "versao": "C300"
    },
    ])
    const styles = StyleSheet.create({
        
    })
    return (
        <View style={{flex: 1, backgroundColor: 'white'}}>
            <ScrollView style={{paddingTop: 10}}>
                <VerticalList data={data}/>
            </ScrollView>
        </View>
    )
}
export default Favorites